# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - webappchatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build backend
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present  # Apenas se houver um script de build no backend

      - name: Zip backend artifact for deployment
        run: zip -r backend-release.zip ./backend  # Compacta a pasta do backend

      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Unzip backend artifact
        run: unzip backend-release.zip -d ./backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F4C143507D764728BE162DBA981B4553 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F27BAECC665C445BB4B7F7E2B7A24F85 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_199A37AE4D1F4298BCC979DC401D4810 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webappchatbot'  # Atualize com o nome do seu app de backend
          slot-name: 'Production'
          package: ./backend  # A pasta que contém o código do seu backend
